title: The open-source project
description: Open-source project (offered by Gerit Wagner)
theme: just-the-docs

url: https://just-the-docs.github.io

repository: digital-work-lab/open-source-project

gh_edit_link: true
gh_edit_link_text: 'Help improve this page'
gh_edit_repository: 'https://github.com/digital-work-lab/open-source-project'
gh_edit_branch: 'main'
gh_edit_view_mode: 'tree'

mermaid:
  version: "11.1.0"

callouts:
  warning:
    title: Warning
    color: red
  deliverable:
    title: Deliverable
    color: yellow
  info:
    color: yellow
  feedback:
    title: Student feedback
    color: blue
  objective:
    title: Learning objective
    color: blue
  see_also:
    title: See also
    color: green

exclude: ['session_5_presentations']

logo: "/assets/images/open-source-project.png"

aux_links:
  "Repository":
    - "https://github.com/digital-work-lab/open-source-project"
  "Improvement":
    - "https://github.com/digital-work-lab/open-source-project/issues"
